version: '3.4'

services:
  dotnetjobs.applicants.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  dotnetjobs.identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  dotnetjobs.jobs.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
